# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trpc.proto\x12\nhelloworld\"\x1e\n\x0b\x45\x63hoRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tEchoReply\x12\x0f\n\x07message\x18\x01 \x01(\t2E\n\x04\x45\x63ho\x12=\n\x0b\x45\x63hoMessage\x12\x17.helloworld.EchoRequest\x1a\x15.helloworld.EchoReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpc_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ECHOREQUEST']._serialized_start=25
  _globals['_ECHOREQUEST']._serialized_end=55
  _globals['_ECHOREPLY']._serialized_start=57
  _globals['_ECHOREPLY']._serialized_end=85
  _globals['_ECHO']._serialized_start=87
  _globals['_ECHO']._serialized_end=156
# @@protoc_insertion_point(module_scope)
